// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bdgrxmskmavfyhmlkzew.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJkZ3J4bXNrbWF2ZnlobWxremV3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjgxNzYwMjUsImV4cCI6MjA4Mzc1MjAyNX0.W6yJUPFJaCBwCEAefBXZZmydQGx_ddHRRgoNVgcn61k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
